### ISSUE TITLE
Jenkins error: GMTool command failed. Error code: 3.Failed to launch virtual device: nexus5

### ISSUE THREAD

**Issue by ralphpina** [Genymobile/genymotion-gradle-plugin#13] opened 2016-01-22 17:28 UTC
Trying to run Genymotion in Jenkins. However, the emulator won't startup. The emulator works fine when started manually. 
- I've put the Genymotion.app and Genymotion Shell inside `/Users/Shared/` so that the `Jenkins` user has access to it.
- The device is listed:
  ![screenshot 2016-01-22 09 25 49](https://cloud.githubusercontent.com/assets/1758274/12517916/2d85b2f8-c0ea-11e5-90aa-ff6c1748e9cb.png)
- And the device starts when clicked manually:
  ![screenshot 2016-01-22 09 27 12](https://cloud.githubusercontent.com/assets/1758274/12517946/583a7952-c0ea-11e5-9726-da33cd1ecfbc.png)

```
genymotion {
    devices {
        nexus5 {
            template "Google Nexus 5 - 5.0.0 - API 21 - 1080x1920"
            deleteWhenFinish false
        }
    }
    config {
        genymotionPath = "/Users/Shared/Genymotion.app/Contents/MacOS/"
        username = "XXX"
        password = "XXX"
        license = "XXX"
    }
}
```

```
:everstore:genymotionLaunchConnectedDebugAndroidTest
com.genymotion.tools.GMToolException: GMTool command failed. Error code: 3.Failed to launch virtual device: nexus5

    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
    at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
    at com.genymotion.tools.GMTool.handleExitValue(GMTool.groovy:1107)
    at com.genymotion.tools.GMTool$handleExitValue$3.callCurrent(Unknown Source)
    at com.genymotion.tools.GMTool.cmd(GMTool.groovy:1012)
    at com.genymotion.tools.GMTool$cmd$9.callCurrent(Unknown Source)
    at com.genymotion.tools.GMTool.cmd(GMTool.groovy:971)
    at com.genymotion.tools.GMTool.cmd(GMTool.groovy)
    at com.genymotion.tools.GMTool$cmd$8.callCurrent(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
    at com.genymotion.tools.GMTool.startDevice(GMTool.groovy:752)
    at com.genymotion.tools.GMTool$startDevice$16.callCurrent(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
    at com.genymotion.tools.GMTool.startDevice(GMTool.groovy:748)
    at com.genymotion.tools.GMTool.startDevice(GMTool.groovy)
    at com.genymotion.model.GenymotionVDLaunch.start(GenymotionVDLaunch.groovy:134)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at com.genymotion.tasks.GenymotionLaunchTask.processDevice(GenymotionLaunchTask.groovy:83)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
    at com.genymotion.tasks.GenymotionLaunchTask$_exec_closure2.doCall(GenymotionLaunchTask.groovy:59)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:439)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1372)
    at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at com.genymotion.tasks.GenymotionLaunchTask.exec(GenymotionLaunchTask.groovy:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
    at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:155)
    at org.gradle.internal.Factories$1.create(Factories.java:22)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:152)
    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:100)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:94)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:94)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
An error occured. Stopping and deleting all launched devices, if needed.
:everstore:genymotionLaunchConnectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':everstore:genymotionLaunchConnectedDebugAndroidTest'.
> com.genymotion.tools.GMToolException: GMTool command failed. GMTool command failed. Error code: 3.Failed to launch virtual device: nexus5
```

**Comment by eyal-lezmy** [comment] 2016-02-06 21:34
Hi Ralf,
Could you please add `genymotion.config.verbose true` to your build.gradle file and add the option `--debug` to your gradle task command and paste the end of the result on this thread?
It will display all the commands launched and their output.

**Comment by eyal-lezmy** [comment] 2016-09-15 08:04
Up on this issue or I will have to close it.

**Comment by ScottBishop** [comment] 2016-10-28 17:24
I am seeing the same error @eyal-lezmy 

```
GMTool command failed. Error code: 3.[Warning] [getSavedHostOnlyInterface] Checking "vboxnet0" interface status (  QHostAddress( "192.168.56.1" )  )
Failed to launch virtual device: nexus5.1_2

        at com.genymotion.tools.GMTool.handleExitValue(GMTool.groovy:1107)
        at com.genymotion.tools.GMTool$handleExitValue$4.callCurrent(Unknown Source)
        at com.genymotion.tools.GMTool.cmd(GMTool.groovy:1012)
        at com.genymotion.tools.GMTool$cmd$7.callCurrent(Unknown Source)
        at com.genymotion.tools.GMTool.cmd(GMTool.groovy:971)
        at com.genymotion.tools.GMTool.cmd(GMTool.groovy)
        at com.genymotion.tools.GMTool$cmd$9.callCurrent(Unknown Source)
        at com.genymotion.tools.GMTool.startDevice(GMTool.groovy:752)
        at com.genymotion.tools.GMTool$startDevice$15.callCurrent(Unknown Source)
        at com.genymotion.tools.GMTool.startDevice(GMTool.groovy:748)
        at com.genymotion.tools.GMTool.startDevice(GMTool.groovy)
        at com.genymotion.tools.GMTool$startDevice$14.call(Unknown Source)
```

**Comment by eyal-lezmy** [comment] 2016-10-29 23:11
@ScottBishop what's the frequency of the problem?
It more seems to be a problem related to the software (not from the plugin). Can you please open a ticket to [the support](https://www.genymotion.com/contact/) including the logs (`gmtool admin logzip ./`)?

**Comment by fschramm001** [comment] 2016-10-31 13:40
same problem here

`Caused by: com.genymotion.tools.GMToolException: GMTool command failed. GMTool command failed. Error code: 3.[Warning] [getSavedHostOnlyInterface] Checking "vboxnet1" interface status (  QHostAddress( "192.168.57.1" )  )
14:33:59 [Warning] [getSavedHostOnlyInterface] Checking "vboxnet0" interface status (  QHostAddress( "192.168.56.1" )  )
14:33:59 Failed to launch virtual device: nexus9
14:33:59 
14:33:59    at com.genymotion.tasks.GenymotionLaunchTask.processDevice(GenymotionLaunchTask.groovy:98)
14:33:59    at com.genymotion.tasks.GenymotionLaunchTask$_exec_closure2.doCall(GenymotionLaunchTask.groovy:59)
14:33:59    at com.genymotion.tasks.GenymotionLaunchTask.exec(GenymotionLaunchTask.groovy:58)
14:33:59    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
14:33:59    ... 21 more`

**Comment by ScottBishop** [comment] 2016-10-31 17:46
@eyal-lezmy It happens about 10 times a day (we have about 10 devs). I will try and get the logs you asked for.

**Comment by suzukieng** [comment] 2017-01-31 11:41
I've been in extensive communication with Genymotion (Damien from support team) about this issue. Crash logs of GMTool indicate that it might be a Qt issue. According to support they are now aware of the problem, but there is no ETA for a fix.

Currently this makes our CI build pretty much unusable. :-(

**Comment by jurenovic** [comment] 2017-04-07 08:22
@eyal-lezmy any news on this one. We are experiencing a lot of this lately...

**Comment by eyal-lezmy** [comment] 2017-04-07 12:25
Hi @jurenovic,

The support team is answering your ticket right now, we need more info.

To all others, `Failed to launch virtual device` is not related to the Gradle plugin himself, I encourage you to contact us through the [Genymotion support team](https://www.genymotion.com/contact/) that will be way more efficient 😄 

I close this ticket as it is not revelant for this project.

**Closed as completed by eyal-lezmy** 2017-04-07 12:25 UTC
