### ISSUE TITLE
Genymotion 2.7.1, genymotionFinish task no longer closes emulators

### ISSUE THREAD

**Issue by juanyanezgc** [Genymobile/genymotion-gradle-plugin#14] opened 2016-06-11 12:01 UTC
Using Genymotion 2.7.1, the genymotionFinish task no longer closes the emulator, it removes them from the system but if they were running they keep running making GMTool not find those devices when trying to run them again

**Comment by eyal-lezmy** [comment] 2016-06-13 07:49
Hi @juanyanezgc,

This seems more related to the soft than the gradle plugin. The better is to send a ticket to the support so we can dig in.

Could you please:
- Add `genymotion.config.verbose true` to your build.gradle and then launch your tests adding option `--debug` to the command. This will display more information about the test process.
- Extract the logs (running `gmtool admin logzip`)
- And then send all these to the support team https://www.genymotion.com/contact/

Cheers

**Comment by eyal-lezmy** [comment] 2016-09-15 08:05
The issue is not related to the gradle plugin. I close this issue.

**Closed as completed by eyal-lezmy** 2016-09-15 08:05 UTC
